# Generated by Django 5.2 on 2025-07-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
