# Generated by Django 5.2 on 2025-07-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='BlogType',
            new_name='blog_type',
        ),
    ]
