# Generated by Django 5.2 on 2025-07-24 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
